export { default as HomePage } from "./HomePage/HomePage"
export { default as ProductDetailpage } from "./ProductDetail/ProductDetailpage"
export { default as Blogpage } from "./Blogpage"
export { default as Aboutpage } from "./Aboutpage"
export { default as Productpage } from "./ProductPage/Productpage"
export { default as CheckoutPage } from "./CheckoutPage/CheckoutPage"
export { default as Cartpage } from "./CartPage/Cartpage"
export { default as AccountPage } from "./AccountPage/AccountPage"
